import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import Feed from '@/components/feed.js'

import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })
import { useAuthState } from 'react-firebase-hooks/auth';

import { auth, firestore } from "@/components/firebase"

export default function Home() {
  let [user] = useAuthState(auth)

  const CreatePost = () => {
    const [website, setWebsite] = useState('')

    const CreatePost = async (e) => {
      e.preventDefault()
      const commentRef = firestore.collection(`websites`);
      var currentdate = new Date();
      await commentRef.add({
          link:website,
          user:user.email,
        
      })
      setWebsite('')
    }
    return (
      <form onSubmit={CreatePost}>
        <label for = 'website'>Create a post</label><br/>
        <input type = 'text' value = {website} onChange={(e) => {setWebsite(e.target.value)}} name = 'website' placeholder = 'Input Website Here' /><br/>
        <input type = 'submit' value = 'Create Post'/>
      </form>
    );
  }
  return (
    <>
      <Head class="padding:5px">
        <title>Main Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {user && <CreatePost/>}
        <Feed/>
      </main>
    </>
  )
}
