import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Post from '../components/post.jsx'

import Feed from '@/components/feed.js'

import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [posts, getPosts] = useState(0);

  const CreatePost = () => {
    return (
      <button>This is a button</button>
    );
  }
  return (
    <>
      <Head class="padding:5px">
        <title>Main Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Feed/>
      </main>
    </>
  )
}
